// Copyright 2026 Avora. All rights reserved.

#ifndef CHROME_BROWSER_AVORA_AVORA_SPACE_ICON_DATA_H_
#define CHROME_BROWSER_AVORA_AVORA_SPACE_ICON_DATA_H_

#include <cstddef>
#include <string_view>

namespace avora {

// One icon in Avora's curated Lucide set.  See avora_space_icons.h for the
// lookup helpers; this header only exists so the generated table in
// avora_space_icon_data.cc has something to define.
struct SpaceIcon {
  // Lucide identifier, e.g. "briefcase".  This is what a Space stores.
  std::string_view id;

  // Human-readable name, shown in the picker and in tooltips.
  std::string_view label;

  // Picker section this icon belongs to, e.g. "Work".  Entries are grouped in
  // catalog order, so all icons of a category are adjacent.
  std::string_view category;

  // SVG path data in Lucide's 24x24 coordinate space.  Monochrome by
  // construction: the geometry carries no colour, which is what lets a Space
  // paint its icon in its own accent colour.
  std::string_view path_data;
};

// Generated by build-scripts/generate_space_icons.py.
extern const SpaceIcon kSpaceIconCatalog[];
extern const size_t kSpaceIconCatalogSize;

}  // namespace avora

#endif  // CHROME_BROWSER_AVORA_AVORA_SPACE_ICON_DATA_H_
