import("//build/config/ui.gni")

source_set("avora") {
  sources = [
    "avora_favorite_tab_marker.cc",
    "avora_favorite_tab_marker.h",
    "avora_favorites_view.cc",
    "avora_favorites_view.h",
    "avora_space_gesture_controller.cc",
    "avora_space_gesture_controller.h",
    "avora_link_preview_view.cc",
    "avora_link_preview_view.h",
    "avora_live_folders_view.cc",
    "avora_live_folders_view.h",
    "avora_pinned_section_view.cc",
    "avora_pinned_section_view.h",
    "avora_quick_nav_view.cc",
    "avora_quick_nav_view.h",
    "avora_sidebar_view.cc",
    "avora_sidebar_view.h",
    "avora_space_label_view.cc",
    "avora_space_label_view.h",
    "avora_spaces_bar_view.cc",
    "avora_spaces_bar_view.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/avora",
    "//chrome/browser/favicon",
    "//chrome/browser/profiles:profile",
    "//components/constrained_window",
    "//components/prefs",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/tabs:tab_strip",
    "//components/favicon/core",
    "//components/favicon_base",
    "//components/vector_icons",
    "//content/public/browser",
    "//extensions/browser",
    "//extensions/common",
    "//services/network/public/cpp",
    "//skia",
    "//ui/base",
    "//ui/events",
    "//ui/gfx",
    "//ui/views",
    "//ui/views/controls/webview",
    "//url",
  ]
}
